Repository BCCF-UBCO-AD/Exercise1, pull requests merged in 2021-09, with the labels that each got.

#13 Update CMakeLists.txt
  CMakeLists.txt
Labels: bug

#12 Merge feat-cmdparse to develop
  main.cpp
Labels: enhancement, Task

#10 Merge develop into master
  CMakeLists.txt
  include/common.h
  include/encrypt-decrypt.h
  include/files.h
  include/md5-duplicate-detection.h
  include/third-party/md5.h
  main.cpp
  src/encrypt-decrypt.cpp
  src/files.cpp
  src/md5-duplicate-detection.cpp
  src/third-party/md5.cpp
  test-files/A
  test-files/B
  test-files/E
  test-files/file.txt
  test-files/file_decrypted.txt
  test-files/file_encrypted.txt
  tests/duplicate-detection.cpp
  tests/encrypt-decrypt.cpp
  tests/files.cpp
Labels: Chore
